name: cvmodels
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - pytorch=1.13.1=py3.9_cuda11.6_cudnn8.3.2_0
  - _libgcc_mutex=0.1=main
  - _pytorch_select=0.2=gpu_0
  - absl-py=1.3.0=py39h06a4308_0
  - aiohttp=3.8.1=py39h7f8727e_1
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - async-timeout=4.0.2=py39h06a4308_0
  - attrs=22.1.0=py39h06a4308_0
  - blas=1.0=mkl
  - blinker=1.4=py39h06a4308_0
  - bottleneck=1.3.4=py39hce1f21e_0
  - brotli=1.0.9=he6710b0_2
  - brotlipy=0.7.0=py39h27cfd23_1003
  - c-ares=1.18.1=h7f8727e_0
  - ca-certificates=2023.05.30=h06a4308_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2023.5.7=py39h06a4308_0
  - cffi=1.15.0=py39hd667e15_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py39h06a4308_0
  - conda=22.11.1=py39h06a4308_5
  - conda-package-handling=2.1.0=py39h06a4308_0
  - conda-package-streaming=0.8.0=py39h06a4308_0
  - cryptography=39.0.1=py39h9ce1e76_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=h70c0345_0
  - frozenlist=1.2.0=py39h7f8727e_0
  - giflib=5.2.1=h7b6447c_0
  - google-auth=2.6.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.4=pyhd3eb1b0_0
  - grpcio=1.42.0=py39hce63b2e_0
  - idna=3.4=py39h06a4308_0
  - importlib-metadata=6.0.0=py39h06a4308_0
  - intel-openmp=2019.4=243
  - jpeg=9e=h7f8727e_0
  - kiwisolver=1.4.2=py39h295c915_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libmklml=2019.0.5=h06a4308_0
  - libopenblas=0.3.13=h4367d64_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.20.1=h4ff587b_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.2.0=h2818925_1
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - lz4-c=1.9.3=h295c915_1
  - markdown=3.4.1=py39h06a4308_0
  - markupsafe=2.1.1=py39h7f8727e_0
  - matplotlib-base=3.5.1=py39ha18d171_1
  - mkl=2020.2=256
  - mkl-service=2.3.0=py39he8ac12f_0
  - mkl_fft=1.3.0=py39h54f3939_0
  - mkl_random=1.0.2=py39h63df603_0
  - multidict=5.2.0=py39h7f8727e_2
  - munkres=1.1.4=py_0
  - ncurses=6.3=h7f8727e_2
  - ninja=1.10.2=h06a4308_5
  - ninja-base=1.10.2=hd09550d_5
  - numexpr=2.7.3=py39hb2eb853_0
  - numpy=1.19.2=py39h89c1606_0
  - numpy-base=1.19.2=py39h2ae0177_0
  - oauthlib=3.2.2=py39h06a4308_0
  - openssl=1.1.1u=h7f8727e_0
  - packaging=23.0=py39h06a4308_0
  - pandas=1.4.2=py39h295c915_0
  - pillow=9.0.1=py39h22f2fdc_0
  - pip=23.0.1=py39h06a4308_0
  - pluggy=1.0.0=py39h06a4308_1
  - protobuf=3.20.1=py39h295c915_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycosat=0.6.3=py39h27cfd23_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyjwt=2.4.0=py39h06a4308_0
  - pyopenssl=23.0.0=py39h06a4308_0
  - pyparsing=3.0.9=py39h06a4308_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.12=h12debd9_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytz=2022.7=py39h06a4308_0
  - pyyaml=6.0=py39h7f8727e_1
  - readline=8.1.2=h7f8727e_1
  - requests=2.29.0=py39h06a4308_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - ruamel.yaml=0.16.12=py39h27cfd23_1
  - ruamel.yaml.clib=0.2.6=py39h7f8727e_0
  - seaborn=0.12.2=py39h06a4308_0
  - setuptools=66.0.0=py39h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.38.5=hc218d9a_0
  - tensorboard=2.11.0=py39h06a4308_0
  - tensorboard-data-server=0.6.0=py39hca6d32c_0
  - tensorboard-plugin-wit=1.8.1=py39h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - toolz=0.12.0=py39h06a4308_0
  - torchvision=0.14.1=py39_cu116
  - tqdm=4.65.0=py39hb070fc8_0
  - typing-extensions=4.5.0=py39h06a4308_0
  - typing_extensions=4.5.0=py39h06a4308_0
  - tzdata=2023c=h04d1e81_0
  - urllib3=1.26.15=py39h06a4308_0
  - werkzeug=2.2.3=py39h06a4308_0
  - wheel=0.38.4=py39h06a4308_0
  - xz=5.2.5=h7f8727e_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.6.3=py39h27cfd23_0
  - zipp=3.11.0=py39h06a4308_0
  - zlib=1.2.12=h7f8727e_2
  - zstandard=0.15.2=py39h27cfd23_0
  - zstd=1.5.2=ha4553b6_0


